### ISSUE TITLE
Crash when adding debater

### ISSUE THREAD

**Issue by JLimperg** [JLimperg/opdtab#10]
When starting OPDtab from a fresh install, clicking the "Add" button in the "Debaters" window crashes the programme.

mono 4.4.1.0
gtk-sharp 2.12.21

This applies to all current binary releases (1.0.6 through 1.1.3).

**Comment by Ferdi811** [comment]
Adding s.th. like

`public void Add(System.Object o) {
    //Relax
}`

to  [opdtab/OPDtabData/Tournament/TeamData.cs](https://github.com/JLimperg/opdtab/blob/master/OPDtabData/Tournament/TeamData.cs) prevents the program from crashing but then the gov/opp-data won't be loaded/saved although the function above doesn't get called at all (according to breakpoints). Weired.
